"""Simplified Chinese glosses for Peppa S01 adult vocabulary (lemma display → 简中, keys lowercased)."""

from __future__ import annotations

import re

LEMMA_ZH: dict[str, str] = {
    "playgroup": "幼儿园游戏小组（幼儿集体游戏班）",
    "brilliant": "太棒了；出色的",
    "dinosaur": "恐龙",
    "there": "那里；那边",
    "petals": "花瓣",
    "stalk": "（花草的）茎；柄",
    "he": "他",
    "gazelle": "羚羊（瞪羚一类）",
    "baa": "羊叫声（咩）",
    "hooray": "好哇；万岁",
    "hurray": "好哇；万岁（读 /həˈreɪ/，勿读成 /ˈhʌreɪ/）",
    "pussycat": "小猫咪（昵称）",
    "fete": "（户外）游园会；义卖会",
    "purr": "（猫）呼噜声",
    "bouncy": "有弹性；蹦跳的",
    "cookie": "小甜饼；曲奇",
    "cooky": "小甜饼（同 cookie）",
    "muddy": "满是泥的",
    "puddle": "水坑；泥坑",
    "puddles": "水坑、泥坑（复数）",
    "hiccupping": "打嗝（动词 -ing）",
    "hiccup": "打嗝",
    "hiccups": "打嗝（名/动复）",
    "beaker": "烧杯；大口杯",
    "grownup": "大人",
    "chloe": "克洛伊（角色名）",
    "skinny legs": "细腿儿（本集蜘蛛梗）",
    "life jackets": "救生衣",
    "lifejackets": "救生衣",
    "hearties": "（海盗口吻）兄弟们；伙计们",
    "braver": "更勇敢",
    "teapot": "茶壶",
    "mister": "先生（称呼）",
    "brown bear": "棕熊",
    "bookshelf": "书架",
    "triceratops": "三角龙",
    "brontosaurus": "雷龙（蜥脚类恐龙）",
    "tyrannosaurus": "霸王龙",
    "untidy": "不整洁",
    "tidying": "收拾；整理",
    "map reading": "读地图",
    "castles": "城堡（复数）",
    "windy": "风大的；多风的",
    "wriggly": "扭来扭去的",
    "froggies": "小青蛙（昵称，复数）",
    "froggy": "小青蛙（昵称）",
    "burp": "打嗝（儿语）",
    "frogs": "青蛙（复数）",
    "worms": "虫子（复数）",
    "butterflies": "蝴蝶（复数）",
    "shiver": "发抖；打哆嗦",
    "mew": "（猫）喵喵叫",
    "goodie": "好东西；奖品（儿语）",
    "reflection": "倒影；反射",
    "polishing": "擦亮；上光",
    "pig this": "这头猪（字幕碎片）",
    "soapy": "多肥皂泡的",
    "helper": "帮手",
    "misty": "有小雾的；朦胧的",
    "parcel": "包裹",
    "mazy": "迷宫似的；曲折的",
    "abracadabra": "变魔术时的咒语腔",
    "o'clock": "……点钟",
    "mysterious": "神秘的",
    "shush": "嘘！（让别人安静）",
    "flipping": "翻面；侧翻（语境：煎饼）",
    "hoopla": "喧闹；小题大作",
    "teatime": "下午茶时间",
    "stirring": "搅拌",
    "pancakes": "煎饼；薄饼（复数）",
    "frighten": "使害怕；吓到",
    "daddy's": "爸爸的（所有格）",
    "muddier": "更脏、更多泥的",
    "might as well": "倒不如；不妨",
    "ice lolly": "冰棍（英式）",
    "paddling": "（在浅水）蹬水玩；划水",
    "should": "应该",
    "melts": "融化（动词第三人称/复数）",
    "oily": "油乎乎的",
    "yucky": "难吃；恶心（儿语）",
    "good that": "那样很好（字幕碎片）",
    "melon": "瓜；甜瓜",
    "piggy": "小猪（昵称）",
    "crisp": "（英式）炸薯片；脆的",
    "goody": "糖果；好东西（儿语）",
    "thunderstorm": "雷暴；雷雨",
    "splash": "溅水；哗啦声",
    "soak": "浸透；泡透",
    "gardening": "园艺；打理花园",
    "mend": "修补；缝补",
    "disturb": "打扰",
    "bicycles": "自行车（复数）",
    "pedaling": "蹬车（骑行）",
    "tricycle": "三轮车",
    "stabilizer": "（童车）辅助轮",
    "rumbling": "隆隆响",
    "listens": "听（第三人称）",
    "you": "你；你们",
    "craftsman": "工匠",
    "wheelbarrow": "独轮手推车",
    "flower pots": "花盆（复数）",
    "flower bed": "花坛",
    "snowball": "雪球",
    "press-ups": "俯卧撑（英式）",
    "pedals": "脚踏板（复数）",
    "pedal": "脚踏板",
    "slippers": "拖鞋",
    "waterhog": "（戏称）水老虎；本集海盗梗",
    "water hog": "见 waterhog",
    "afloat": "漂浮",
    "aye-aye": "（航海）遵命",
    "ayeaye": "（航海）遵命",
    "sea dog": "老水手（戏称）",
    "granddad": "爷爷；外公",
    "ahoy": "喂！（船上招呼）",
    "grandpa": "爷爷；外公",
    "snore": "打鼾",
    "puppet": "木偶",
    "doughnut": "甜甜圈",
    "decorate": "装饰",
    "imago": "成虫；（心理）理想化形象",
    "sandcastle": "沙堡",
    "splashing": "拍水；溅水",
    "splish": "（拟声）扑哧水声",
    "splosh": "（拟声）哗啦",
    "towels": "毛巾（复数）",
    "beach bag": "沙滩包",
    "sunshade": "遮阳伞；遮篷",
    "tickles": "挠痒痒；（第三人称）发痒",
    "plaster": "灰泥；腻子（装修）",
    "well done": "干得好；（肉）全熟",
    "ohayo": "你好／早（日语腔，非规范拼写）",
    "erm": "呃……（迟疑）",
    "suppertime": "晚饭时间",
    "chloe's": "克洛伊的（所有格）",
    "every way": "各方面",
    "sleepy": "困的",
    "jeté": "（芭蕾）小跳",
    "demi-plié": "（芭蕾）半蹲",
    "children": "孩子们",
    "photos": "照片（复数）",
    "gonna": "将要（口语，= going to）",
    "horticulturist": "园艺家",
    "icelandic": "冰岛的；冰岛语",
    "darlings": "亲爱的们",
    "lobbing": "高高甩出",
    "lopping": "砍剪",
    "accordion": "手风琴",
    "could": "能（can 的过去式）",
    "george": "乔治（角色名）",
    "rabbit": "兔子",
    "scarier": "更吓人",
    "pig your": "你的猪（字幕碎片）",
    "dog goodbye": "跟狗说再见（字幕碎片）",
    "goodbye bye": "再见再见（儿语）",
    "garage": "车库",
    "car can": "车能……（字幕碎片）",
    "too don": "太……（字幕碎片）",
    "yes but": "是的但是（字幕碎片）",
    "luckiest": "最幸运",
    "dress": "连衣裙",
    "fancy": "花哨的；化装的",
    "party": "聚会",
    "school play": "校园剧",
    "lunch": "午餐",
    "picnic blanket": "野餐垫",
    "piggy in the middle": "中间的小猪（游戏名）",
    "playground": "游乐场；操场",
    "picnic": "野餐",
    "lemonade": "柠檬水",
    "parrot": "鹦鹉",
    "polly": "波莉（鹦鹉名）",
    "peppa": "佩奇（角色名）",
    "lipstick": "口红",
    "fooled": "骗了；上当",
    "snort": "（猪等）鼻息声；鼻哼一声",
    "petit saut": "（芭蕾）小跳",
    "arms graceful": "双臂舒展、姿态优雅（芭蕾字幕碎片）",
    "dancing": "跳舞",
    "bye-bye": "拜拜；再见",
    "good now": "这就对了；现在好了（字幕碎片）",
    "too, don't you": "……是吧？……对吗？（too, don't you 连写碎片）",
    "yes, but": "是的，但是（字幕碎片）",
    "argh": "啊！唉哟！（疼痛、懊恼叫声）",
    "gavesgate": "加夫斯盖特（本集虚构／综艺式玫瑰品种名）",
    "ha-ha": "哈哈（笑声）",
    "Grandpa Pig": "猪爷爷（角色）",
    "Granny Pig": "猪奶奶（角色）",
    "water wings": "（学游泳用的）臂圈；浮力袖",
    "babysitting": "临时照看小孩",
    "tease": "逗弄；取笑；招惹",
    "chirp": "（鸟）啁啾；叽喳叫",
    "peg": "木栓；钉；（帐篷）地钉",
    "draught": "穿堂风；通风气流（英式拼写）",
    "pajama": "睡衣（口语单数，常作 pajamas）",
    "shining": "闪亮；发光；光辉",
    "food spaghetti": "吃的意大利面（字幕粘连碎片）",
    "saw": "看见（see 的过去式）；锯子",
    "pedalling": "蹬车；踩踏板（英式拼写，= pedaling）",
    "garage": "车库；修车铺",
    "car": "汽车",
    "tuck in": "开动吧；尽情吃（开餐用语）",
}

# Canonical lookup keys are lowercased (source entries may use Title Case for readability).
LEMMA_ZH = {k.lower(): v for k, v in LEMMA_ZH.items()}


def zh_for_lemma(lemma: str, fallback_gloss: str) -> str:
    key = lemma.strip()
    low = key.lower()
    if low in LEMMA_ZH:
        return LEMMA_ZH[low]
    base = low[:-2] if (low.endswith("'s") and len(low) > 2) else None
    if base and base in LEMMA_ZH:
        return LEMMA_ZH[base] + "（所有格）"
    fg = (fallback_gloss or "").strip()
    if fg and not fg.startswith("字幕笔误") and re.search(r"[\u4e00-\u9fff]", fg):
        return fg
    return f"（请补义项：{lemma}）"
